-- begin SAMPLEPROJECT_SKILL
alter table SAMPLEPROJECT_SKILL add constraint FK_SAMPLEPROJECT_SKILL_ON_SKILLCATEGORY foreign key (SKILLCATEGORY_ID) references SAMPLEPROJECT_SKILLCATEGORY(ID)^
create index IDX_SAMPLEPROJECT_SKILL_ON_SKILLCATEGORY on SAMPLEPROJECT_SKILL (SKILLCATEGORY_ID)^
-- end SAMPLEPROJECT_SKILL
-- begin SAMPLEPROJECT_USER_SKILL_LINK
alter table SAMPLEPROJECT_USER_SKILL_LINK add constraint FK_SAMPLEPROJECT_USER_SKILL_LINK_ON_SKILL foreign key (SKILL_ID) references SAMPLEPROJECT_SKILL(ID)^
alter table SAMPLEPROJECT_USER_SKILL_LINK add constraint FK_SAMPLEPROJECT_USER_SKILL_LINK_ON_USER foreign key (USER_ID) references SAMPLEPROJECT_USER(ID)^
create index IDX_SAMPLEPROJECT_USER_SKILL_LINK_ON_SKILL on SAMPLEPROJECT_USER_SKILL_LINK (SKILL_ID)^
create index IDX_SAMPLEPROJECT_USER_SKILL_LINK_ON_USER on SAMPLEPROJECT_USER_SKILL_LINK (USER_ID)^
-- end SAMPLEPROJECT_USER_SKILL_LINK
